version: '3'
  
services:
 acbridge:
  image: samsung_ac
  command: /usr/local/bin/homebridge -U /var/lib/homebridge
  volumes:
   - ./samsung_ac/homebridge:/var/lib/homebridge
  container_name: samsung_ac
  restart: always
  network_mode: host
  ports:
   - "30212:30212"
